const ERRORS = {
  CUSTOMER_NOT_FOUND: "CUSTOMER_NOT_FOUND",
  CUSTOMERS_MULTIPLE_FOUND: "CUSTOMERS_MULTIPLE_FOUND",
  DOCUMENT_NOT_FOUND: "DOCUMENT_NOT_FOUND",
  DOCUMENT_CREATE_ERROR: "DOCUMENT_CREATE_ERROR",
  CUSTOMER_CREATE_ERROR: "CUSTOMER_CREATE_ERROR",
  DOCUMENT_UPDATESTEP_ERROR: "DOCUMENT_UPDATESTEP_ERROR",
  DOCUMENT_CREATEPAYMENT_ERROR: "DOCUMENT_CREATEPAYMENT_ERROR",
};

export default ERRORS;
